'use client';
import { ChevronsRight, Coins, FlaskConical, Heart, MessageCircle, Mountain, Skull, Sparkles, Swords, Target, Users, Volume2, VolumeX, Waves, Zap, Droplets, Flame, Wind, } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PixelPanel } from './pixel';
import { ELEMENT_MAP } from './element-data';
export type GameAction = 'attack' | 'skill0' | 'skill1' | 'skill2' | 'skill3' | 'potion' | 'interact';
export interface SkillInfoLite { name: string; archetype: string; cd: number; ch: number; range?: number }
type BarProps = { pct: number; color: string; bg: string; h?: number; label?: any };
type SkillButtonProps = {
  icon: any; hotkey?: string; cdLeft: number; cdTotal: number; cost?: number; count?: number;
  disabled?: boolean; elementColor?: string; onTrigger: () => void; size?: 'md' | 'lg'; title?: string;
};
const BASE_ICONS = { fogo: Flame, agua: Droplets, raio: Zap, vento: Wind, terra: Mountain };
export function skillIcon(element, archetype) { switch (archetype) { case 'dash': return ChevronsRight; case 'multi': return Sparkles; case 'line': return Waves; case 'aoe': return Target; default: return BASE_ICONS[element] || Sparkles; } }
function Bar({ pct, color, bg, h = 14, label }: BarProps) { return (<div className="relative w-full overflow-hidden border border-[#00000066]" style={{ height: h, background: bg }}><div className="h-full transition-[width] duration-200" style={{ width: `${Math.max(0, Math.min(100, pct))}%`, background: color }}/>{label ? <span className="font-retro absolute inset-0 flex items-center justify-center text-[13px] leading-none text-white drop-shadow-[1px_1px_0_rgba(0,0,0,0.9)]">{label}</span> : null}</div>); }
function PlayerFrame({ hud, element }) { const info=ELEMENT_MAP[element],hpPct=hud.hp/Math.max(1,hud.mh)*100,chPct=hud.ch/Math.max(1,hud.mc)*100,xpPct=hud.xp/Math.max(1,hud.need)*100; return (<PixelPanel className="pointer-events-none w-[230px] sm:w-[260px] !p-2 sm:!p-3"><div className="mb-1.5 flex items-center justify-between gap-2"><div className="flex items-center gap-1.5"><span className="font-pixel text-[9px] text-[#ffb347]">Nv{hud.lvl}</span><span className="font-retro truncate text-lg leading-none text-[#e8d5a9]">Você</span></div><span className="font-retro border px-1 text-[13px] leading-tight" style={{color:info.color,borderColor:`${info.color}88`}}>{info.jutsuStyle}</span></div><div className="space-y-1"><Bar pct={hpPct} color="linear-gradient(180deg,#6ee06e,#3da63d)" bg="#274a1e" label={`${hud.hp} / ${hud.mh}`}/><Bar pct={chPct} color="linear-gradient(180deg,#5bb8e8,#2f7fb5)" bg="#1e3a4a" h={10} label={`${hud.ch} / ${hud.mc}`}/><Bar pct={xpPct} color="linear-gradient(180deg,#f97316,#c2410c)" bg="#3a2410" h={5}/></div><div className="font-retro mt-1.5 flex items-center justify-between text-[13px] text-[#a89b7d]"><span className="flex items-center gap-1"><Coins className="h-3.5 w-3.5 text-[#f0d060]"/> {hud.gold} ryō</span><span className="flex items-center gap-1"><FlaskConical className="h-3.5 w-3.5 text-[#e88a8a]"/> {hud.pot}</span><span className="hidden items-center gap-1 sm:flex"><Heart className="h-3.5 w-3.5 text-[#4ade80]"/> {hud.zoneName}</span></div></PixelPanel>); }
function MissionTracker({hud}){if(!hud.mission)return null;const pct=hud.mission.prog/hud.mission.need*100;return <PixelPanel className="pointer-events-none mt-2 w-[230px] sm:w-[260px] !p-2"><div className="font-pixel mb-1 text-[8px] tracking-wider text-[#f0d060]">MISSÃO</div><div className="font-retro mb-1 truncate text-[15px] leading-tight text-[#e8d5a9]">{hud.mission.name}</div><Bar pct={pct} color="linear-gradient(180deg,#f0d060,#b8860b)" bg="#3a2f14" h={8} label={`${hud.mission.prog} / ${hud.mission.need}`}/></PixelPanel>}
function BossBar({boss}){return <div className="pointer-events-none absolute left-1/2 top-14 z-20 w-[min(440px,86vw)] -translate-x-1/2 sm:top-16"><PixelPanel className="!p-2"><div className="mb-1 flex items-center justify-between"><span className="flex items-center gap-1.5"><Skull className="h-4 w-4 text-[#ff6060]"/><span className="font-pixel text-[9px] text-[#ff8080]">{boss.n}</span></span><span className="font-retro text-[13px] text-[#a89b7d]">{Math.ceil(boss.pct)}%</span></div><Bar pct={boss.pct} color="linear-gradient(180deg,#e6392b,#8a1a10)" bg="#3a0e08" h={12}/></PixelPanel></div>}
export function ZoneBanner({zone,safe}){return <div className="pointer-events-none absolute left-1/2 top-3 z-20 -translate-x-1/2 text-center sm:top-4" style={{animation:'zone-banner 2.8s ease forwards'}}><div className="font-pixel text-[11px] tracking-widest text-[#e8d5a9] drop-shadow-[2px_2px_0_rgba(0,0,0,0.9)] sm:text-sm">{zone}</div><div className={`font-retro mt-1 text-sm tracking-wide ${safe?'text-[#7dff7d]':'text-[#ff8080]'}`}>{safe?'— ZONA SEGURA —':'— ZONA DE PERIGO —'}</div></div>}
export function SkillButton({icon:Icon,hotkey,cdLeft,cdTotal,cost,count,disabled=false,elementColor,onTrigger,size='md',title}: SkillButtonProps){const onCd=cdLeft>0,pct=cdTotal>0?cdLeft/cdTotal*100:0;return <button type="button" title={title} aria-label={title} onPointerDown={e=>{e.preventDefault();if(!onCd&&!disabled)onTrigger()}} className={`relative ${size==='lg'?'h-16 w-16':'h-12 w-12 sm:h-14 sm:w-14'} select-none border-2 ${disabled?'border-[#3a2f22] opacity-45':'border-[#5a4a32] active:translate-y-[2px]'} bg-[#211a12] shadow-[3px_3px_0_rgba(0,0,0,0.5)] transition-transform`} style={{touchAction:'none'}}><Icon className="mx-auto h-6 w-6" style={{color:elementColor||'#e8d5a9'}}/>{hotkey?<span className="font-pixel absolute left-0.5 top-0.5 text-[7px] text-[#a89b7d]">{hotkey}</span>:null}{cost!=null?<span className={`font-retro absolute bottom-0 right-0.5 text-[12px] leading-none ${disabled?'text-[#ff6060]':'text-[#5bb8e8]'}`}>{cost}</span>:null}{count!=null?<span className="font-retro absolute bottom-0 right-0.5 text-[12px] leading-none text-[#e88a8a]">x{count}</span>:null}{onCd?<><span className="absolute inset-0" style={{background:`conic-gradient(rgba(0,0,0,0.72) ${pct*3.6}deg, transparent 0deg)`}}/><span className="font-retro absolute inset-0 flex items-center justify-center text-xl text-white">{cdLeft>=1000?`${Math.ceil(cdLeft/1000)}s`:`${Math.ceil(cdLeft/100)/10}`}</span></>:null}</button>}
function SkillBar({hud,skills,element,onAction}){const info=ELEMENT_MAP[element];return <div className="pointer-events-auto absolute bottom-3 left-1/2 z-20 -translate-x-1/2 sm:bottom-4"><div className="flex items-end gap-1.5 sm:gap-2"><SkillButton icon={Swords} hotkey="ESP" cdLeft={hud.cds[0].left} cdTotal={hud.cds[0].total} title="Ataque de kunai" onTrigger={()=>onAction('attack')}/>{skills.map((s,i)=><SkillButton key={i} icon={skillIcon(element,s.archetype)} hotkey={String(i+1)} cdLeft={hud.cds[1+i].left} cdTotal={hud.cds[1+i].total} cost={s.ch} disabled={hud.ch<s.ch} elementColor={info.color} title={`${s.name} — ${s.ch} chakra, recarga ${Math.round(s.cd/1000)}s`} onTrigger={()=>onAction(`skill${i}`)}/>)}<SkillButton icon={FlaskConical} hotkey="Q" cdLeft={hud.cds[5].left} cdTotal={hud.cds[5].total} count={hud.pot} title="Poção — cura 55% do HP" onTrigger={()=>onAction('potion')}/></div></div>}
function InteractHint({hud,isTouch,onInteract}){if(!hud.interact)return null;const label=hud.interact==='fonte'?'Beber da fonte (cura total)':'Ichiraku — comprar poção (25 ryō)';return <button type="button" onClick={onInteract} className="font-retro pointer-events-auto absolute bottom-20 left-1/2 z-20 -translate-x-1/2 border-2 border-[#f0d060] bg-[#1a1410ee] px-4 py-1.5 text-base text-[#f0d060] shadow-[3px_3px_0_rgba(0,0,0,0.5)] active:translate-y-[1px] sm:bottom-24">{isTouch?'▸ ':'[E] '}{label}</button>}
function DeathOverlay({deathBy,onRespawn}){return <div className="pointer-events-auto absolute inset-0 z-40 flex items-center justify-center bg-[#0f0d0acc] backdrop-blur-[2px]"><PixelPanel className="w-[min(420px,88vw)] !p-5 text-center" title="VOCÊ FOI DERROTADO"><div className="font-retro my-3 text-lg text-[#e8d5a9]">{deathBy?<>O <span className="text-[#ff8080]">{deathBy}</span> venceu esta batalha...</>:'Um shinobi sabe quando recuar.'}</div><div className="font-retro mb-4 text-[15px] text-[#a89b7d]">Sem perda de XP — renasça e tente de novo!</div><Button onClick={onRespawn} className="h-auto w-full rounded-none border-2 border-[#f97316] bg-[#f97316] py-3 font-pixel text-[10px] text-[#1a0e05] shadow-[4px_4px_0_rgba(0,0,0,0.5)] hover:bg-[#ea580c] active:translate-x-[2px] active:translate-y-[2px]">RENASCER NA VILA</Button></PixelPanel></div>}
export function Hud(props){const{hud,isTouch}=props;return <><div className="pointer-events-none absolute left-2 top-2 z-20 sm:left-3 sm:top-3"><PlayerFrame hud={hud} element={props.element}/><div className="hidden sm:block"><MissionTracker hud={hud}/></div></div>{isTouch&&hud.mission?<div className="font-retro pointer-events-none absolute left-2 top-[118px] z-20 max-w-[180px] text-[12px] leading-tight text-[#e8d5a9] drop-shadow-[1px_1px_0_rgba(0,0,0,0.9)]"><span className="text-[#f0d060]">Missão:</span> {hud.mission.name} ({hud.mission.prog}/{hud.mission.need})</div>:null}{hud.boss?<BossBar boss={hud.boss}/>:null}{!isTouch?<SkillBar hud={hud} skills={props.skills} element={props.element} onAction={props.onAction}/>:null}<InteractHint hud={hud} isTouch={isTouch} onInteract={()=>props.onAction('interact')}/>{hud.dead?<DeathOverlay deathBy={props.deathBy} onRespawn={props.onRespawn}/>:null}<div className="font-retro pointer-events-none absolute bottom-1 right-2 z-10 text-[13px] text-[#6b5f4a]">{hud.fps} fps</div></>}
export function TopRightCluster({online,muted,playersOpen,chatOpen,isTouch,onToggleMute,onTogglePlayers,onToggleChat}){const btn='pointer-events-auto flex h-8 w-8 items-center justify-center border-2 border-[#5a4a32] bg-[#211a12] text-[#e8d5a9] shadow-[2px_2px_0_rgba(0,0,0,0.5)] active:translate-y-[1px]';return <div className="absolute right-2 top-2 z-30 flex flex-col items-end gap-1.5 sm:right-3 sm:top-3"><div className="font-retro flex items-center gap-1.5 border-2 border-[#3a2f22] bg-[#1a1410dd] px-2 py-0.5 text-[13px] text-[#7dff7d]"><span className="inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-[#7dff7d]"/>{online} online</div><div className="flex gap-1.5"><button type="button" className={btn} onClick={onTogglePlayers} aria-label="Jogadores online" title="Jogadores online"><Users className={`h-4 w-4 ${playersOpen?'text-[#ffb347]':''}`}/></button><button type="button" className={btn} onClick={onToggleMute} aria-label={muted?'Ativar som':'Silenciar'} title={muted?'Ativar som':'Silenciar'}>{muted?<VolumeX className="h-4 w-4"/>:<Volume2 className="h-4 w-4"/>}</button>{isTouch?<button type="button" className={btn} onClick={onToggleChat} aria-label="Chat" title="Chat"><MessageCircle className={`h-4 w-4 ${chatOpen?'text-[#ffb347]':''}`}/></button>:null}</div></div>}
